### ISSUE TITLE
Handle active courses from previous semesters

### ISSUE THREAD

**Issue by parth-io** [k-walter/canvas-downloader#15]
Currently, `canvas-downloader` downloads courses from the past semester as well because they show up as active courses . This is annoying because I want to free up space from my hard disk (one course takes up 400MB because of videos).

Canvas returns this additional field `enrollment_term_id` in its API response for courses which can be used to identify the current active semester. For AY22-23 S2, this id is `120`. For AY22-23 S1, it was `115`, so I'm guessing it increments every month.

Two approaches:
Either use this `enrollment_term_id` as below in this hacky approach at line 86 of main.rs:

```
    let current_enrollment_term = json!(120);
    let default_term = json!(0);

    for course_json in courses_json.as_array().unwrap() {
        if course_json.get("enrollments").is_some() && (*(course_json.get("enrollment_term_id").unwrap_or(&default_term)) == current_enrollment_term) {
```

Or specify the courses you want to download in a `toml`/`txt` file, which is inconvenient but certain.

Which one sounds more reasonable?

**Comment by JingYenLoh** [comment]
What about an option to specify the current enrollment term instead? Say `--term 120`. That will allow the user to fetch from previous terms as well.

Might want to consider an argparser as well with this, I personally like clap.

**Comment by k-walter** [comment]
Sounds good! We are indeed using clap. Do assign yourself if you're interested in working on it.
